# Question B1 (15 marks)

Real world datasets often have a mix of numeric and categorical features – this dataset is one example. To build models on such data, categorical features have to be encoded or embedded.

PyTorch Tabular is a library that makes it very convenient to build neural networks for tabular data. It is built on top of PyTorch Lightning, which abstracts away boilerplate model training code and makes it easy to integrate other tools, e.g. TensorBoard for experiment tracking.

For questions B1 and B2, the following features should be used:   
- **Numeric / Continuous** features: dist_to_nearest_stn, dist_to_dhoby, degree_centrality, eigenvector_centrality, remaining_lease_years, floor_area_sqm
- **Categorical** features: month, town, flat_model_type, storey_range



---

In [3]:
!pip install "pytorch_tabular[extra]"

Collecting pytorch_tabular[extra]
  Downloading pytorch_tabular-1.2.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: torch>=1.11.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (2.5.1+cu121)
Requirement already satisfied: numpy<=3.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (1.26.4)
Collecting pandas<3.0.0,>=1.1.5 (from pytorch_tabular[extra])
  Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: scikit-learn<2.0,>=1.3.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (1.8.0)
Collecting pytorch-lightning<2.7.0,>=2.0.0 (from pytorch_tabular[extra])
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: scipy<2.0,>=1.8 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (1.17.1)
Collecting omegaconf>=2.3.0 (from pytorch_tabular[extra])
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting torchmetrics<1.9.0,>=0.10.0 (from pytorch_tabular[extra])
  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)
Collecting einops<0.9.0,>=0.6.0 (from pytorch_tabular[extra])
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: rich>=11.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (13.7.1)
Collecting scikit-base (from pytorch_tabular[extra])
  Downloading scikit_base-0.13.1-py3-none-any.whl.metadata (8.8 kB)
Collecting wandb<0.19.0,>=0.15.0 (from pytorch_tabular[extra])
  Downloading wandb-0.18.7-py3-none-win_amd64.whl.metadata (9.7 kB)
Requirement already satisfied: plotly<5.25.0,>=5.13.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch_tabular[extra]) (5.24.1)
Collecting kaleido<0.3.0,>=0.2.0 (from pytorch_tabular[extra])
  Downloading kaleido-0.2.1-py2.py3-none-win_amd64.whl.metadata (15 kB)
Collecting captum<0.8.0,>=0.5.0 (from pytorch_tabular[extra])
  Downloading captum-0.7.0-py3-none-any.whl.metadata (26 kB)
Collecting pytorch-tabnet<4.2 (from pytorch_tabular[extra])
  Downloading pytorch_tabnet-4.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: matplotlib in c:\users\chooz\anaconda3\lib\site-packages (from captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (3.9.2)
Requirement already satisfied: tqdm in c:\users\chooz\anaconda3\lib\site-packages (from captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (4.67.3)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf>=2.3.0->pytorch_tabular[extra])
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: PyYAML>=5.1.0 in c:\users\chooz\anaconda3\lib\site-packages (from omegaconf>=2.3.0->pytorch_tabular[extra]) (6.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chooz\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.1.5->pytorch_tabular[extra]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chooz\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.1.5->pytorch_tabular[extra]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chooz\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.1.5->pytorch_tabular[extra]) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\chooz\anaconda3\lib\site-packages (from plotly<5.25.0,>=5.13.0->pytorch_tabular[extra]) (8.2.3)
Requirement already satisfied: packaging in c:\users\chooz\anaconda3\lib\site-packages (from plotly<5.25.0,>=5.13.0->pytorch_tabular[extra]) (26.0)
Requirement already satisfied: fsspec>=2022.5.0 in c:\users\chooz\anaconda3\lib\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (2024.6.1)
Requirement already satisfied: typing-extensions>4.5.0 in c:\users\chooz\anaconda3\lib\site-packages (from pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (4.15.0)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra])
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\chooz\anaconda3\lib\site-packages (from rich>=11.0.0->pytorch_tabular[extra]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\chooz\anaconda3\lib\site-packages (from rich>=11.0.0->pytorch_tabular[extra]) (2.15.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\chooz\anaconda3\lib\site-packages (from scikit-learn<2.0,>=1.3.0->pytorch_tabular[extra]) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\chooz\anaconda3\lib\site-packages (from scikit-learn<2.0,>=1.3.0->pytorch_tabular[extra]) (3.6.0)
Requirement already satisfied: filelock in c:\users\chooz\anaconda3\lib\site-packages (from torch>=1.11.0->pytorch_tabular[extra]) (3.13.1)
Requirement already satisfied: networkx in c:\users\chooz\anaconda3\lib\site-packages (from torch>=1.11.0->pytorch_tabular[extra]) (3.3)
Requirement already satisfied: jinja2 in c:\users\chooz\anaconda3\lib\site-packages (from torch>=1.11.0->pytorch_tabular[extra]) (3.1.4)
Requirement already satisfied: setuptools in c:\users\chooz\anaconda3\lib\site-packages (from torch>=1.11.0->pytorch_tabular[extra]) (78.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\chooz\anaconda3\lib\site-packages (from torch>=1.11.0->pytorch_tabular[extra]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\chooz\anaconda3\lib\site-packages (from sympy==1.13.1->torch>=1.11.0->pytorch_tabular[extra]) (1.3.0)
Requirement already satisfied: click!=8.0.0,>=7.1 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (8.1.7)
Collecting docker-pycreds>=0.4.0 (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra])
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (3.1.43)
Requirement already satisfied: platformdirs in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (3.10.0)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (4.25.3)
Requirement already satisfied: psutil>=5.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (5.9.0)
Requirement already satisfied: requests<3,>=2.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in c:\users\chooz\anaconda3\lib\site-packages (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (2.18.0)
Collecting setproctitle (from wandb<0.19.0,>=0.15.0->pytorch_tabular[extra])
  Downloading setproctitle-1.3.7-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: colorama in c:\users\chooz\anaconda3\lib\site-packages (from click!=8.0.0,>=7.1->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (0.4.6)
Requirement already satisfied: six>=1.4.0 in c:\users\chooz\anaconda3\lib\site-packages (from docker-pycreds>=0.4.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (1.17.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\chooz\anaconda3\lib\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (3.10.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\chooz\anaconda3\lib\site-packages (from gitpython!=3.1.29,>=1.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (4.0.7)
Requirement already satisfied: mdurl~=0.1 in c:\users\chooz\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=11.0.0->pytorch_tabular[extra]) (0.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chooz\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chooz\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chooz\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chooz\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\chooz\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->pytorch_tabular[extra]) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\chooz\anaconda3\lib\site-packages (from matplotlib->captum<0.8.0,>=0.5.0->pytorch_tabular[extra]) (3.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\chooz\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch_tabular[extra]) (1.11.0)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\chooz\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb<0.19.0,>=0.15.0->pytorch_tabular[extra]) (4.0.0)
Downloading captum-0.7.0-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 9.8 MB/s eta 0:00:00
Downloading einops-0.8.2-py3-none-any.whl (65 kB)
Downloading kaleido-0.2.1-py2.py3-none-win_amd64.whl (65.9 MB)
   ---------------------------------------- 0.0/65.9 MB ? eta -:--:--
    --------------------------------------- 1.6/65.9 MB 8.4 MB/s eta 0:00:08
   - -------------------------------------- 3.1/65.9 MB 7.7 MB/s eta 0:00:09
   --- ------------------------------------ 5.2/65.9 MB 8.4 MB/s eta 0:00:08
   ---- ----------------------------------- 7.3/65.9 MB 8.9 MB/s eta 0:00:07
   ----- ---------------------------------- 8.9/65.9 MB 8.5 MB/s eta 0:00:07
   ------ --------------------------------- 10.0/65.9 MB 8.1 MB/s eta 0:00:07
   ------ --------------------------------- 11.5/65.9 MB 8.0 MB/s eta 0:00:07
   ------- -------------------------------- 13.1/65.9 MB 7.8 MB/s eta 0:00:07
   --------- ------------------------------ 15.2/65.9 MB 8.1 MB/s eta 0:00:07
   ---------- ----------------------------- 17.3/65.9 MB 8.3 MB/s eta 0:00:06
   ----------- ---------------------------- 19.4/65.9 MB 8.4 MB/s eta 0:00:06
   ------------- -------------------------- 21.5/65.9 MB 8.5 MB/s eta 0:00:06
   ------------- -------------------------- 23.1/65.9 MB 8.5 MB/s eta 0:00:06
   --------------- ------------------------ 24.9/65.9 MB 8.5 MB/s eta 0:00:05
   ---------------- ----------------------- 26.7/65.9 MB 8.6 MB/s eta 0:00:05
   ----------------- ---------------------- 28.6/65.9 MB 8.6 MB/s eta 0:00:05
   ------------------ --------------------- 30.4/65.9 MB 8.6 MB/s eta 0:00:05
   ------------------- -------------------- 32.2/65.9 MB 8.6 MB/s eta 0:00:04
   -------------------- ------------------- 33.8/65.9 MB 8.5 MB/s eta 0:00:04
   --------------------- ------------------ 35.4/65.9 MB 8.5 MB/s eta 0:00:04
   ---------------------- ----------------- 36.7/65.9 MB 8.4 MB/s eta 0:00:04
   ----------------------- ---------------- 38.5/65.9 MB 8.4 MB/s eta 0:00:04
   ------------------------ --------------- 40.6/65.9 MB 8.5 MB/s eta 0:00:03
   ------------------------- -------------- 42.7/65.9 MB 8.6 MB/s eta 0:00:03
   --------------------------- ------------ 44.6/65.9 MB 8.6 MB/s eta 0:00:03
   ---------------------------- ----------- 46.4/65.9 MB 8.6 MB/s eta 0:00:03
   ----------------------------- ---------- 48.0/65.9 MB 8.6 MB/s eta 0:00:03
   ----------------------------- ---------- 49.3/65.9 MB 8.5 MB/s eta 0:00:02
   ------------------------------ --------- 50.6/65.9 MB 8.4 MB/s eta 0:00:02
   ------------------------------- -------- 52.2/65.9 MB 8.4 MB/s eta 0:00:02
   -------------------------------- ------- 53.7/65.9 MB 8.3 MB/s eta 0:00:02
   --------------------------------- ------ 55.8/65.9 MB 8.4 MB/s eta 0:00:02
   ----------------------------------- ---- 58.5/65.9 MB 8.5 MB/s eta 0:00:01
   ------------------------------------ --- 60.6/65.9 MB 8.6 MB/s eta 0:00:01
   ------------------------------------- -- 61.9/65.9 MB 8.5 MB/s eta 0:00:01
   -------------------------------------- - 64.0/65.9 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------  65.8/65.9 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 65.9/65.9 MB 8.4 MB/s eta 0:00:00
Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.0 MB 8.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/11.0 MB 7.7 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.0 MB 7.4 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 8.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.0 MB 8.2 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.0 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 7.4 MB/s eta 0:00:00
Downloading pytorch_lightning-2.6.1-py3-none-any.whl (857 kB)
   ---------------------------------------- 0.0/857.3 kB ? eta -:--:--
   ---------------------------------------- 857.3/857.3 kB 7.6 MB/s eta 0:00:00
Downloading pytorch_tabnet-4.1.0-py3-none-any.whl (44 kB)
Downloading torchmetrics-1.8.2-py3-none-any.whl (983 kB)
   ---------------------------------------- 0.0/983.2 kB ? eta -:--:--
   ---------------------------------------- 983.2/983.2 kB 5.8 MB/s eta 0:00:00
Downloading wandb-0.18.7-py3-none-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/15.5 MB 8.3 MB/s eta 0:00:02
   -------- ------------------------------- 3.4/15.5 MB 8.4 MB/s eta 0:00:02
   -------------- ------------------------- 5.5/15.5 MB 9.1 MB/s eta 0:00:02
   ---------------- ----------------------- 6.3/15.5 MB 8.8 MB/s eta 0:00:02
   --------------------- ------------------ 8.4/15.5 MB 8.3 MB/s eta 0:00:01
   ------------------------- -------------- 10.0/15.5 MB 8.2 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.5 MB 8.2 MB/s eta 0:00:01
   ---------------------------------- ----- 13.4/15.5 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 8.2 MB/s eta 0:00:00
Downloading pytorch_tabular-1.2.0-py3-none-any.whl (165 kB)
Downloading scikit_base-0.13.1-py3-none-any.whl (159 kB)
Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Downloading setproctitle-1.3.7-cp312-cp312-win_amd64.whl (13 kB)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py): started
  Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144616 sha256=a1b9eb07ab2a7c13c5a2b0fd442a9607a4936ad293ebc185d9fef69b17ec4ba8
  Stored in directory: c:\users\chooz\appdata\local\pip\cache\wheels\1f\be\48\13754633f1d08d1fbfc60d5e80ae1e5d7329500477685286cd
Successfully built antlr4-python3-runtime
Installing collected packages: kaleido, antlr4-python3-runtime, setproctitle, scikit-base, omegaconf, lightning-utilities, einops, docker-pycreds, pandas, wandb, torchmetrics, pytorch-tabnet, captum, pytorch-lightning, pytorch_tabular
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.1
    Uninstalling pandas-3.0.1:
      Successfully uninstalled pandas-3.0.1
Successfully installed antlr4-python3-runtime-4.9.3 captum-0.7.0 docker-pycreds-0.4.0 einops-0.8.2 kaleido-0.2.1 lightning-utilities-0.15.3 omegaconf-2.3.0 pandas-2.3.3 pytorch-lightning-2.6.1 pytorch-tabnet-4.1.0 pytorch_tabular-1.2.0 scikit-base-0.13.1 setproctitle-1.3.7 torchmetrics-1.8.2 wandb-0.18.7

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\chooz\anaconda3\Lib\site-packages\~-ndas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\chooz\anaconda3\Lib\site-packages\~-ndas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires packaging<25,>=20, but you have packaging 26.0 which is incompatible.

In [1]:
SEED = 42

import os

import random
random.seed(SEED)

import numpy as np
np.random.seed(SEED)

import pandas as pd

from pytorch_tabular import TabularModel
from pytorch_tabular.models import CategoryEmbeddingModelConfig
from pytorch_tabular.config import (
    DataConfig,
    OptimizerConfig,
    TrainerConfig,
)

from sklearn.metrics import mean_squared_error, r2_score

1.Divide the dataset (‘hdb_price_prediction.csv’) into train, validation and test sets by using entries from year 2019 and before as training data, year 2020 as validation data and year 2021 as test data.
**Do not** use data from year 2022 and year 2023.

In [6]:
df = pd.read_csv('hdb_price_prediction.csv')

# YOUR CODE HERE

# Filter Out data from year 2022 and 2023
df = df[df['year'].isin([2019, 2020, 2021]) | (df['year'] < 2019)]

# Define features that should be used
numeric_features     = ['dist_to_nearest_stn', 'dist_to_dhoby', 'degree_centrality', 'eigenvector_centrality', 'remaining_lease_years', 'floor_area_sqm']
categorical_features = ['month', 'town', 'flat_model_type', 'storey_range']
prediction_target    = ['resale_price']
all_features         = numeric_features + categorical_features + prediction_target

# Split features for train, validation & test by year
train_df = df[df['year'] <= 2019]
val_df   = df[df['year'] == 2020]
test_df  = df[df['year'] == 2021]

# Separate features and target
train_df = train_df[all_features]
val_df   = val_df[all_features]
test_df  = test_df[all_features]

In [7]:
display(train_df)

,dist_to_nearest_stn,dist_to_dhoby,degree_centrality,eigenvector_centrality,remaining_lease_years,floor_area_sqm,month,town,flat_model_type,storey_range,resale_price
0,1.007264,7.006044,0.016807,0.006243,61.333333,44.0,1,ANG MO KIO,"2 ROOM, Improved",10 TO 12,232000.0
1,1.271389,7.983837,0.016807,0.006243,60.583333,67.0,1,ANG MO KIO,"3 ROOM, New Generation",01 TO 03,250000.0
2,1.069743,9.090700,0.016807,0.002459,62.416667,67.0,1,ANG MO KIO,"3 ROOM, New Generation",01 TO 03,262000.0
3,0.946890,7.519889,0.016807,0.006243,62.083333,68.0,1,ANG MO KIO,"3 ROOM, New Generation",04 TO 06,265000.0
4,1.092551,9.130489,0.016807,0.002459,62.416667,67.0,1,ANG MO KIO,"3 ROOM, New Generation",01 TO 03,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
64052,0.823163,14.421823,0.016807,0.000382,67.583333,142.0,12,YISHUN,"EXECUTIVE, Apartment",04 TO 06,580000.0
64053,0.823163,14.421823,0.016807,0.000382,67.583333,146.0,12,YISHUN,"EXECUTIVE, Maisonette",07 TO 09,565000.0
64054,0.445869,13.498243,0.016807,0.000968,71.500000,164.0,12,YISHUN,"EXECUTIVE, Apartment",01 TO 03,633000.0
64055,0.552769,13.598257,0.016807,0.000968,71.500000,164.0,12,YISHUN,"EXECUTIVE, Apartment",10 TO 12,788888.0
64056,0.475885,12.738721,0.016807,0.000968,67.083333,145.0,12,YISHUN,"EXECUTIVE, Maisonette",07 TO 09,618000.0

In [10]:
display(val_df)

,dist_to_nearest_stn,dist_to_dhoby,degree_centrality,eigenvector_centrality,remaining_lease_years,floor_area_sqm,month,town,flat_model_type,storey_range,resale_price
64057,0.917344,7.336493,0.016807,0.006243,55.583333,73.0,1,ANG MO KIO,"3 ROOM, New Generation",04 TO 06,265000.0
64058,0.696776,7.341622,0.016807,0.006243,91.666667,70.0,1,ANG MO KIO,"3 ROOM, Model A",19 TO 21,470000.0
64059,0.597608,7.292217,0.016807,0.006243,56.333333,73.0,1,ANG MO KIO,"3 ROOM, New Generation",01 TO 03,230000.0
64060,0.994153,7.427003,0.016807,0.006243,55.250000,73.0,1,ANG MO KIO,"3 ROOM, New Generation",04 TO 06,280000.0
64061,0.921541,8.163605,0.016807,0.006243,59.083333,68.0,1,ANG MO KIO,"3 ROOM, New Generation",07 TO 09,220000.0
...,...,...,...,...,...,...,...,...,...,...,...
87365,1.153544,14.075870,0.016807,0.000382,66.666667,146.0,12,YISHUN,"EXECUTIVE, Maisonette",04 TO 06,560000.0
87366,1.254784,13.948192,0.016807,0.000382,66.750000,145.0,12,YISHUN,"EXECUTIVE, Apartment",01 TO 03,540000.0
87367,0.466763,13.426086,0.016807,0.000968,66.000000,142.0,12,YISHUN,"EXECUTIVE, Apartment",13 TO 15,638000.0
87368,0.281375,12.884815,0.016807,0.000968,66.166667,146.0,12,YISHUN,"EXECUTIVE, Maisonette",10 TO 12,683500.0
87369,0.408137,12.745325,0.016807,0.000968,65.916667,142.0,12,YISHUN,"EXECUTIVE, Apartment",07 TO 09,670000.0

In [12]:
display(test_df)

,dist_to_nearest_stn,dist_to_dhoby,degree_centrality,eigenvector_centrality,remaining_lease_years,floor_area_sqm,month,town,flat_model_type,storey_range,resale_price
87370,1.276775,8.339960,0.016807,0.002459,64.083333,45.0,1,ANG MO KIO,"2 ROOM, Improved",01 TO 03,211000.0
87371,1.276775,8.339960,0.016807,0.002459,64.083333,45.0,1,ANG MO KIO,"2 ROOM, Improved",07 TO 09,225000.0
87372,0.884872,6.981730,0.016807,0.006243,59.000000,68.0,1,ANG MO KIO,"3 ROOM, New Generation",04 TO 06,260000.0
87373,0.677246,8.333056,0.016807,0.006243,58.166667,68.0,1,ANG MO KIO,"3 ROOM, New Generation",04 TO 06,265000.0
87374,0.922047,8.009223,0.016807,0.006243,58.083333,68.0,1,ANG MO KIO,"3 ROOM, New Generation",01 TO 03,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
116422,0.954699,13.018048,0.016807,0.000968,95.083333,112.0,12,YISHUN,"5 ROOM, Improved",13 TO 15,720000.0
116423,0.475885,12.738721,0.016807,0.000968,65.083333,142.0,12,YISHUN,"EXECUTIVE, Apartment",01 TO 03,738000.0
116424,0.408137,12.745325,0.016807,0.000968,65.000000,146.0,12,YISHUN,"EXECUTIVE, Maisonette",04 TO 06,755000.0
116425,0.733238,14.183095,0.016807,0.000382,90.916667,112.0,12,YISHUN,"5 ROOM, DBSS",10 TO 12,848000.0
116426,0.774113,13.229106,0.016807,0.000968,65.083333,171.0,12,YISHUN,"MULTI-GENERATION, Multi Generation",07 TO 09,865000.0

In [14]:
# Make sure data sets have no null values
print(train_df.isnull().sum().sum())
print(val_df.isnull().sum().sum())
print(test_df.isnull().sum().sum())

0
0
0

2.Refer to the documentation of **PyTorch Tabular** and perform the following tasks: https://pytorch-tabular.readthedocs.io/en/latest/#usage
- Use **[DataConfig](https://pytorch-tabular.readthedocs.io/en/latest/data/)** to define the target variable, as well as the names of the continuous and categorical variables.
- Use **[TrainerConfig](https://pytorch-tabular.readthedocs.io/en/latest/training/)** to automatically tune the learning rate. Set batch_size to be 1024 and set max_epoch as 50.
- Use **[CategoryEmbeddingModelConfig](https://pytorch-tabular.readthedocs.io/en/latest/models/#category-embedding-model)** to create a feedforward neural network with 1 hidden layer containing 50 neurons.
- Use **[OptimizerConfig](https://pytorch-tabular.readthedocs.io/en/latest/optimizer/)** to choose Adam optimiser. There is no need to set the learning rate (since it will be tuned automatically) nor scheduler.
- Use **[TabularModel](https://pytorch-tabular.readthedocs.io/en/latest/tabular_model/)** to initialise the model and put all the configs together.

In [17]:
batch_size = 1024
max_epochs = 50
layers = '50'
optimizer = 'Adam'

In [19]:
# YOUR CODE HERE

data_config = DataConfig(
    target = prediction_target, 
    continuous_cols = numeric_features, 
    categorical_cols = categorical_features
)

trainer_config = TrainerConfig(
    auto_lr_find = True, 
    batch_size = batch_size, 
    max_epochs = max_epochs
)

model_config = CategoryEmbeddingModelConfig(
    task = 'regression', 
    layers = layers, 
)

optimizer_config = OptimizerConfig(
    optimizer = optimizer
)

tabular_model = TabularModel(
    data_config = data_config, 
    model_config = model_config, 
    optimizer_config = optimizer_config, 
    trainer_config = trainer_config
)

2026-03-09 20:12:13,123 - {pytorch_tabular.tabular_model:145} - INFO - Experiment Tracking is turned off

In [21]:
# Train the model
tabular_model.fit(train = train_df, validation = val_df)

Seed set to 42
2026-03-09 20:12:16,408 - {pytorch_tabular.tabular_model:547} - INFO - Preparing the DataLoaders
2026-03-09 20:12:16,473 - {pytorch_tabular.tabular_datamodule:527} - INFO - Setting up the datamodule for regression task
2026-03-09 20:12:16,713 - {pytorch_tabular.tabular_model:598} - INFO - Preparing the Model: CategoryEmbeddingModel
2026-03-09 20:12:16,830 - {pytorch_tabular.tabular_model:341} - INFO - Preparing the Trainer
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\logger_connector\logger_connector.py:76: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
2026-03-09 20:12:17,159 - {pytorch_tabular.tabular_model:655} - INFO - Auto LR Find Started
You are using a CUDA device ('NVIDIA GeForce RTX 2050') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\chooz\OneDrive\Documents\SC4001 Neural Network\SC4001 Assignment\saved_models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
`weights_only` was not set, defaulting to `False`.
C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Finding best initial lr:   0%|          | 0/100 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_steps=100` reached.
Restoring states from the checkpoint path at C:\Users\chooz\OneDrive\Documents\SC4001 Neural Network\SC4001 Assignment\.lr_find_3bd6074e-5496-465b-842e-b7286146f093.ckpt
C:\Users\chooz\anaconda3\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Restored all states from the checkpoint at C:\Users\chooz\OneDrive\Documents\SC4001 Neural Network\SC4001 Assignment\.lr_find_3bd6074e-5496-465b-842e-b7286146f093.ckpt
Learning rate set to 2.7542287033381663e-05
2026-03-09 20:12:26,109 - {pytorch_tabular.tabular_model:668} - INFO - Suggested LR: 2.7542287033381663e-05. For plot and detailed analysis, use `find_learning_rate` method.
2026-03-09 20:12:26,111 - {pytorch_tabular.tabular_model:677} - INFO - Training Started
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  2.9 K │ train │     0 │
│ 1 │ _embedding_layer │ Embedding1dLayer          │  1.5 K │ train │     0 │
│ 2 │ head             │ LinearHead                │     51 │ train │     0 │
│ 3 │ loss             │ MSELoss                   │      0 │ train │     0 │
└───┴──────────────────┴───────────────────────────┴────────┴───────┴───────┘

Trainable params: 4.5 K
Non-trainable params: 0
Total params: 4.5 K
Total estimated model params size (MB): 0
Modules in train mode: 16
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=50` reached.

2026-03-09 20:17:41,005 - {pytorch_tabular.tabular_model:690} - INFO - Training the model completed
2026-03-09 20:17:41,007 - {pytorch_tabular.tabular_model:1531} - INFO - Loading the best model
C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_tabular\utils\python_utils.py:92: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(f, map_location=map_location)  # for torch version < 2.6

3.Report the test MSE error and the test R2 value that you obtained.

In [23]:
# YOUR CODE & RESULT HERE
evaluation = tabular_model.evaluate(test_df)
pred_df = tabular_model.predict(test_df)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Output()

C:\Users\chooz\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:434: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_loss         │      287991529472.0       │
│  test_mean_squared_error  │      287991529472.0       │
└───────────────────────────┴───────────────────────────┘

In [26]:
test_values  = test_df['resale_price'].values
pred_values  = pred_df['resale_price_prediction'].values

# Calculate MSE and R2
test_mse = mean_squared_error(test_values, pred_values)
test_r2  = r2_score(test_values, pred_values)

print(f"Test MSE: {test_mse:.4f}")
print(f"Test R2:  {test_r2:.4f}")

Test MSE: 287991537572.3084
Test R2:  -9.8873

4.Print out the corresponding rows in the dataframe for the top 20 test samples with the largest errors. Are there any patterns or common characteristics among these data points? Based on your observations, suggest and briefly explain a potential strategy to improve the model on these cases.

In [44]:
# YOUR CODE & RESULT HERE

errors = np.abs(test_values - pred_values)

# Get top 20 largest errors
top20_indices = np.argsort(errors)[-20:][::-1]
top20_df = test_df.iloc[top20_indices].copy()
top20_df['predicted_price'] = pred_values[top20_indices]
top20_df['absolute_error'] = errors[top20_indices]

print("Top 20 Test Samples with the Largest Errors:")
display(top20_df.sort_values('absolute_error', ascending = False))

Top 20 Test Samples with the Largest Errors:

,dist_to_nearest_stn,dist_to_dhoby,degree_centrality,eigenvector_centrality,remaining_lease_years,floor_area_sqm,month,town,flat_model_type,storey_range,resale_price,predicted_price,absolute_error
90608,0.776182,6.297489,0.033613,0.015854,88.833333,120.0,12,BISHAN,"5 ROOM, DBSS",37 TO 39,1360000.0,2.891364,1.359997e+06
106199,0.584731,3.882019,0.016807,0.008342,93.333333,122.0,12,QUEENSTOWN,"5 ROOM, Premium Apartment Loft",40 TO 42,1328000.0,4.643356,1.327995e+06
90483,0.767244,6.327956,0.033613,0.015854,89.000000,120.0,9,BISHAN,"5 ROOM, DBSS",37 TO 39,1295000.0,4.889019,1.294995e+06
93931,0.352779,2.413099,0.033613,0.121082,88.083333,107.0,12,CENTRAL AREA,"5 ROOM, Type S2",40 TO 42,1288000.0,5.689346,1.287994e+06
93930,0.438348,2.506568,0.033613,0.121082,88.166667,107.0,12,CENTRAL AREA,"5 ROOM, Type S2",46 TO 48,1280000.0,6.224119,1.279994e+06
90432,0.827889,6.370404,0.033613,0.015854,88.916667,120.0,8,BISHAN,"5 ROOM, DBSS",25 TO 27,1280000.0,6.917776,1.279993e+06
100836,0.998313,3.304953,0.016807,0.053004,50.083333,210.0,6,KALLANG/WHAMPOA,"3 ROOM, Terrace",01 TO 03,1268000.0,1.831578,1.267998e+06
101237,0.352251,2.587444,0.016807,0.004414,88.250000,119.0,11,KALLANG/WHAMPOA,"5 ROOM, DBSS",40 TO 42,1268000.0,2.434384,1.267998e+06
93904,0.401367,2.445314,0.033613,0.121082,88.333333,106.0,11,CENTRAL AREA,"5 ROOM, Type S2",40 TO 42,1261000.0,6.128878,1.260994e+06
90523,0.776182,6.297489,0.033613,0.015854,88.916667,120.0,10,BISHAN,"5 ROOM, DBSS",22 TO 24,1260000.0,7.799955,1.259992e+06
92443,0.586629,2.932814,0.016807,0.047782,96.583333,113.0,11,BUKIT MERAH,"5 ROOM, Improved",40 TO 42,1256000.0,12.103970,1.255988e+06
93929,0.352779,2.413099,0.033613,0.121082,88.083333,106.0,12,CENTRAL AREA,"5 ROOM, Type S2",43 TO 45,1254000.0,3.818938,1.253996e+06
90253,0.776182,6.297489,0.033613,0.015854,89.416667,120.0,4,BISHAN,"5 ROOM, DBSS",31 TO 33,1250000.0,5.143315,1.249995e+06
92340,0.451387,2.128424,0.016807,0.047782,90.750000,114.0,10,BUKIT MERAH,"5 ROOM, Improved",34 TO 36,1245000.0,13.431047,1.244987e+06
112973,0.471864,4.101820,0.016807,0.036944,89.500000,114.0,11,TOA PAYOH,"5 ROOM, DBSS",40 TO 42,1240000.0,7.335106,1.239993e+06
90431,0.767244,6.327956,0.033613,0.015854,89.083333,120.0,8,BISHAN,"5 ROOM, DBSS",22 TO 24,1240000.0,7.827225,1.239992e+06
90340,0.767244,6.327956,0.033613,0.015854,89.250000,120.0,6,BISHAN,"5 ROOM, DBSS",25 TO 27,1238800.0,5.767604,1.238794e+06
93670,0.428356,8.948410,0.016807,0.001358,66.666667,154.0,12,BUKIT TIMAH,"EXECUTIVE, Maisonette",04 TO 06,1238000.0,7.386663,1.237993e+06
112731,0.461414,4.151360,0.016807,0.017995,89.833333,114.0,8,TOA PAYOH,"5 ROOM, DBSS",40 TO 42,1238000.0,8.627151,1.237991e+06
101087,0.987682,3.383526,0.016807,0.053004,49.833333,241.0,9,KALLANG/WHAMPOA,"3 ROOM, Terrace",01 TO 03,1235000.0,2.857535,1.234997e+06